### ISSUE TITLE
Fails on some files when being used during FEL baking

### ISSUE THREAD

**Issue by jessielw** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#67] opened 2024-07-26 19:56 UTC
It happens once maybe every 5 different remuxes I process while encoding with `x265` in `2-pass` mode. 

Basic avs script that it would fail on:
```
LWLibavVideoSource("BL.mkv")
bl=ConvertBits(16)
LWLibavVideoSource("EL.mkv")
el=ConvertBits(16)
DoviBaker(bl, el, "el_RPU.bin", outYUV=true)
z_ConvertFormat(pixel_type="yuv420p10", dither_type="error_diffusion")
```

Basic vpy script that it would fail on:
```
import awsmfunc as awf

src = core.lsmas.LWLibavSource("source.mkv")
el = core.lsmas.LWLibavSource("EL.mkv")
src = awf.MapDolbyVision(src, el)

src = src.std.Crop(top=276, bottom=276)
# ... the rest of your filtering
src = vsutil.depth(src, 10, dither_type="error_diffusion")
```

Error:
```
x265 [FLAW]: 2nd pass has more frames than 1st pass (171176 vs 171173)
x265 [FLAW]: x265_encoder_open() failed for Enc, 
```

Utilizing `FFMS2` or `DGDecNV` results in completed encodes/outputs. However, there is some caveats. It's hard to reproduce, it requires the **full** file to reproduce. Testing it with just a small snip doesn't make the crash happen. The file in question is around **70GB**. If you would like to contact me I could FTP it to you or something of that nature so you could test it yourself if required/desired. Also, it fails when swapping from the **first pass** to the **second pass**. Meaning you will have to encode the entire **first pass** to reproduce it.

**Comment by Asd-g** [comment] 2024-08-04 18:55
If you run only the script (for avs with avsmeter, avsr, ffmpeg, for vs with vspipe), is there a crash?

**Comment by jessielw** [comment] 2024-08-04 21:18
So, testing a sample this is the error we get when using `LWLibavVideoSource` when using `avsbenchmark`. 

![image](https://github.com/user-attachments/assets/55fa5f2c-ed6d-4629-b058-019b7d2893ec)

This is for `info`
![image](https://github.com/user-attachments/assets/d48bf0cb-9ee5-4476-bd19-4d67b6202889)

**Comment by Asd-g** [comment] 2024-08-06 23:49
Sent an email for the video file.

**Comment by jessielw** [comment] 2024-08-07 02:36
Grabbing the source again as I must have deleted it. I'll have it uploaded and i'll send you the link tomorrow before the afternoon.
________________________________

**Comment by jessielw** [comment] 2024-08-07 15:53
Let me know once you have the file!

https://drive.google.com/file/d/16gVyoD4LbZn6nQNjYBX89_ODaAVQGbIT/view?usp=sharing
________________________________

**Comment by Asd-g** [comment] 2024-08-08 21:22
Thanks. Downloaded. I'll take a look later.

**Comment by jessielw** [comment] 2024-08-08 21:45
Awesome, let me know what you come up with!

**Comment by Asd-g** [comment] 2024-08-09 14:33
There is archive password.

**Comment by jessielw** [comment] 2024-08-09 14:38
> There is archive password.

Sorry, I believe it is just `lsmash`. Grabbing it again to confirm, I'll have the file in 15 minutes.

**Comment by L4cache** [comment] 2024-08-10 13:11
Where is EL?

**Comment by jessielw** [comment] 2024-08-10 14:30
I provided it via email to the author. The EL is inside the source.

**Comment by L4cache** [comment] 2024-08-10 15:28
> I provided it via email to the author. The EL is inside the source.

Sorry but the link is visible here... (you might want to remove it?)
I just didn't realized that it's a combined file.

**Comment by jessielw** [comment] 2024-08-10 16:28
Thanks, I wonder what the point is sending something via email if it just publicly displays it? 🤣 

But yes, in a **remux** the **EL** layer is embedded into the video stream.

**Comment by L4cache** [comment] 2024-08-10 21:38
At frame 171174 LWLibavSource can't or didn't insert RPU to frame props (FFMS2 can) and placebo.Tonemap crashed because of it. That's the culprit.

**Comment by jessielw** [comment] 2024-08-10 23:29
> At frame 171174 (second last frame) LWLibavSource can't or didn't insert RPU to frame props (FFMS2 can) and placebo.Tonemap crashed because of it. That's the culprit.

If this _was_ the case, why does **FFMS2** not fail under the same conditions?

**Comment by L4cache** [comment] 2024-08-11 00:07
> (FFMS2 can)

I didn't mean the file lacks RPU.
FFMS2 doesn't have the same problem.

LWLibavSource:
![Untitled1 vpy-171174-0](https://github.com/user-attachments/assets/a1302718-10d9-4979-8fe3-2dca279521f3)
FFMS2:
![Untitled1 vpy-171174-1](https://github.com/user-attachments/assets/4cc59b55-133d-4bb7-92bc-6ace2c87a4d1)

**Comment by jessielw** [comment] 2024-08-11 00:43
It's reproducible every single time for sure!

**Comment by Asd-g** [comment] 2024-08-11 08:42
`ffprobe -i 1917.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR.mkv -show_frames -select_streams v:0 > log.txt`
When viewing `log.txt`, you will see that the frame before last doesn't have `side_data_type=Dolby Vision RPU Data`. This is the reason why `L-SMASH-Works` doesn't set `DolbyVisionRPU` frame prop for this frame.

`ffms2` for this frame specifically also doesn't retrieve any rpu data but it uses already retrieved from previous frame(s).

I suggest to ask for fixing the video file so the rpu data is signaled for every frame.

**Comment by jessielw** [comment] 2024-08-11 15:26
> ffprobe -i 1917.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR.mkv -show_frames -select_streams v:0 > log.txt
> When viewing log.txt, you will see that the frame before last doesn't have side_data_type=Dolby Vision RPU Data. This is the reason why L-SMASH-Works doesn't set DolbyVisionRPU frame prop for this frame.
> 
> ffms2 for this frame specifically also doesn't retrieve any rpu data but it uses already retrieved from previous frame(s).
> 
> I suggest to ask for fixing the video file so the rpu data is signaled for every frame.

Unfortunately this is _quite_ common when it comes to dolby vision sources. This can happen directly from the BluRay source in my experience. Is there a suggested work flow for fixing a video file or should L-Smash work like FFMS2 in this case?

**Comment by L4cache** [comment] 2024-08-11 20:19
>Btw using [the latest ffms2 release](https://codeberg.org/StvG/ffms2/releases) the frame type is B.

I'm using FFMS2 version from https://github.com/FFMS/ffms2/releases/tag/5.0, is this version have some problem compared to the one you linked?

**Comment by jessielw** [comment] 2024-08-11 21:32
> > Btw using [the latest ffms2 release](https://codeberg.org/StvG/ffms2/releases) the frame type is B.
> 
> I'm using FFMS2 version from https://github.com/FFMS/ffms2/releases/tag/5.0, is this version have some problem compared to the one you linked? Also I use .hevc raw bitstream produced by dovi_tool, is FFMS2 better with MP4/MKV containers?

I believe these are two different forks. If you notice on the original repo it was 4 years without updates. https://github.com/FFMS/ffms2/releases

Where as stvg has updated his fork several times on doom9 etc. https://codeberg.org/StvG/ffms2/releases

I'm not sure of how different they are and which would be considered _better_.

**Comment by Asd-g** [comment] 2024-08-11 23:10
> Unfortunately this is _quite_ common when it comes to dolby vision sources. This can happen directly from the BluRay source in my experience. Is there a suggested work flow for detecting this issue and fixing the video file before processing or should L-Smash work like FFMS2 in this case?

Can you name such UHD-BD source that cause this issue? The UHD-BD (m2ts) has the streams separated while remuxes (mkv) have the streams merged. I've been told that the incorrectly merged streams can be the cause for this issue (old makemkv). Also remuxing the file with new makemkv should fix the issue.

To check if a remux has this issue you can use that ffprobe line I shared and check if the rpu side data exist for latest few frames. Or you can use this avs script:
```
LWLibavVideoSource(....)
ScriptClip("""
n = 0
for (i = 0, FrameCount() - 1)
{
current_frame = i
if (propGetType("DolbyVisionRPU") == 0)
{
    n = 1
}
}
return n == 1 ? Subtitle("no rpu") : Subtitle("ok")
""")
```

I wouldn't change the behavior for setting `DolbyVisionRPU` frame prop to what ffms2 does (in case of missing rpu side data to use the buffer from the previous frame).

As to ffms2... I tested the ffms2 - both [5.0](https://github.com/FFMS/ffms2/releases/tag/5.0) and [5.0-RC4](https://github.com/FFMS/ffms2/releases/tag/5.0-RC4) have wrong `_PictType` while [5.0-RC3](https://github.com/FFMS/ffms2/releases/tag/5.0-RC3) is ok.
I use ffms2 only for `mkv` and raw streams (`h264`, `hevc`...).
I use ffms2 from codeberg because I tested it before and the changes usually does not introduce regressions.
You can report the picture type regression on the official repo (https://github.com/FFMS/ffms2).

**Comment by jessielw** [comment] 2024-08-12 12:54
> Can you name such UHD-BD source that cause this issue? The UHD-BD (m2ts) has the streams separated while remuxes (mkv) have the streams merged. I've been told that the incorrectly merged streams can be the cause for this issue (old makemkv). Also remuxing the file with new makemkv should fix the issue.

Sorry, I meant remuxes ripped directly from the BluRay disc. I realize in my initial statement that's not what I said. Do you think it would be possible to "repair" a remux that was generated with the _older_ version of makemkv that would cause this error? I haven't tested it yet, but I wonder if **dovi_tool** demux/remux would repair such an issue, or even mkvmerge? 

> To check if a remux has this issue you can use that ffprobe line I shared and check if the rpu side data exist for latest few frames. Or you can use this avs script:

Thanks for the script! I'll likely setup some sort of check to run through it with VapourSynth/python based on the script you provided above!

> I wouldn't change the behavior for setting DolbyVisionRPU frame prop to what ffms2 does (in case of missing rpu side data to use the buffer from the previous frame).

I understand, this makes sense!

> As to ffms2... I tested the ffms2 - both [5.0](https://github.com/FFMS/ffms2/releases/tag/5.0) and [5.0-RC4](https://github.com/FFMS/ffms2/releases/tag/5.0-RC4) have wrong _PictType while [5.0-RC3](https://github.com/FFMS/ffms2/releases/tag/5.0-RC3) is ok.
> I use ffms2 only for mkv and raw streams (h264, hevc...).
> I use ffms2 from codeberg because I tested it before and the changes usually does not introduce regressions.
> You can report the picture type regression on the official repo (https://github.com/FFMS/ffms2).

Thanks for the detailed responses/information on this subject. I can report the regression there.

**Comment by Asd-g** [comment] 2024-08-12 14:22
> Do you think it would be possible to "repair" a remux that was generated with the older version of makemkv that would cause this error? I haven't tested it yet, but I wonder if dovi_tool demux/remux would repair such an issue, or even mkvmerge?

I cut a small sample of the end of the video file. `dovi_tool` and `mkvmerge` cannot repair the issue. Using the latest `makemkv` fixes the issue.

**Comment by L4cache** [comment] 2024-08-12 14:46
> > Do you think it would be possible to "repair" a remux that was generated with the older version of makemkv that would cause this error? I haven't tested it yet, but I wonder if dovi_tool demux/remux would repair such an issue, or even mkvmerge?
> 
> I cut a small sample of the end of the video file. `dovi_tool` and `mkvmerge` cannot repair the issue. Using the latest `makemkv` fixes the issue.

Maybe you can send the sample to https://github.com/FFMS/ffms2/issues/445?

**Comment by jessielw** [comment] 2024-08-12 16:32
> I cut a small sample of the end of the video file. dovi_tool and mkvmerge cannot repair the issue. Using the latest makemkv fixes the issue.
Thanks for looking into it for me! Again, I appreciate you taking the time and explaining things.

> Maybe you can send the sample to https://github.com/FFMS/ffms2/issues/445?
I sent the full size file and the sample links to them

**Closed** 2024-08-14 12:08 UTC
