### ISSUE TITLE
Decoding error with latest build in RipBot264

### ISSUE THREAD

**Issue by Axiom21** [HomeOfAviSynthPlusEvolution/L-SMASH-Works#27] opened 2022-12-19 07:26 UTC
Have just noticed a Decoding Error with 20221109, in RipBot264, when importing new encoding job.
Can't tell you anymore than that, reverted back to the previous, 20220505, and the error has gone.
However, it only seems to be on certain random video files...which adds to the confusion.

**Comment by Asd-g** [comment] 2022-12-20 22:36
Isn't there a log file?

**Comment by Axiom21** [comment] 2022-12-20 23:35
As far as I know, there isn't a log file, and it's because it doesn't create a new Job, due to the Decoding Error, so hence, no log :(
It IS random, so hard to replicate.

**Comment by Asd-g** [comment] 2023-02-02 00:53
I can do nothing if I can't reproduce the error. Also I don't know what's the RipBot264 version. Does the script have only LSmash/LWLibav... call?

I'm closing this. If a way to reproduce this issue is provided, reopen.

**Closed by Asd-g** 2023-02-02 00:53 UTC
